services:
  srm.app:
    image: srm_test_app
    container_name: srm.app
    build:
      context: .
      dockerfile: srm.test.dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5000
      - SUNRAYSMARKET_DbConnection__Host=srm.postgres.db
      - SUNRAYSMARKET_DbConnection__Database=srm_db
      - SUNRAYSMARKET_DbConnection__Username=srm_user
      - SUNRAYSMARKET_DbConnection__Password=BadPass@123
      - SUNRAYSMARKET_DbConnection__Port=5432
      - SUNRAYSMARKET_Stripe__SecretKey=${STRIPE_KEY}
      - SUNRAYSMARKET_SuperAdminUser__Email=${SUPERADMIN_EMAIL}
      - SUNRAYSMARKET_SuperAdminUser__Password=${SUPERADMIN_PASSWORD}
      - SUNRAYSMARKET_SuperAdminUser__FirstName=${SUPERADMIN_FIRSTNAME}
      - SUNRAYSMARKET_SuperAdminUser__LastName=${SUPERADMIN_LASTNAME}
    volumes:
      - ~/.aspnet/https:/https:ro
  
  postgres.db:
    image: postgres:latest
    container_name: srm.postgres.db
    environment:
      - POSTGRES_DB=srm_db
      - POSTGRES_USER=srm_user
      - POSTGRES_PASSWORD=BadPass@123*
    expose:
      - 5432
    volumes:
      - ./.containers/srm-db:/var/lib/postgres/data